apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::252703795646:role/eksctl-first-cluster-cluste-FargatePodExecutionRole-jFo3t2wJuGu0
      username: system:node:{{SessionName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-09T23:40:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1364"
  uid: 74c4f08d-aa94-442f-99c5-2994d5215740
